CREATE TABLE USUARIO
(
  NOME VARCHAR2(250) NOT NULL,
  EMAIL VARCHAR2(250) NOT NULL,
  SENHA VARCHAR2(100) NOT NULL,
  TELEFONE VARCHAR2(10) NOT NULL,
  CONSTRAINT USUARIO_PK PRIMARY KEY 
  (
    EMAIL
  )
  ENABLE
);

CREATE TABLE TELEFONE
(
  DDD NUMBER NOT NULL,
  NUMERO VARCHAR2(10) NOT NULL,
  TIPO VARCHAR2(250) NOT NULL,
  CONSTRAINT TELEFONE_PK PRIMARY KEY
  (
    NUMERO
  )
  ENABLE
);

ALTER TABLE USUARIO ADD CONSTRAINT FK_TELEFONE
  FOREIGN KEY(TELEFONE) REFERENCES
  TELEFONE(NUMERO);